name: .NET Core

on:
  push:
    branches: [ Perf ]
  pull_request:
    branches: [ Perf ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --no-restore "/home/runner/work/BlazorTourOfHeroes/BlazorTourOfHeroes/TourofHeroes/TourofHeroes.csproj"
    - name: GitHub Pages action
      uses: drud/action-cross-commit@master
      with:
       source-folder: /TourofHeroes/bin/Release/netstandard2.1/wwwroot
       destination-repository: https://gopkumr:${{ secrets.user_token }}@github.com/gopkumr/BlazorHost
       destination-folder: .
       destination-branch: master
       git-user: gopkumr 
       git-user-email: gopakumar.r@live.com
        
