name: .NET Core

on:
  push:
    branches: [ Perf ]
  pull_request:
    branches: [ Perf ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --no-restore "/home/runner/work/BlazorTourOfHeroes/BlazorTourOfHeroes/TourofHeroes/TourofHeroes.csproj"
    - name: Publish to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
      with:
        # The name of the directory that containing the content to be published
        dir: /home/runner/work/BlazorTourOfHeroes/BlazorTourOfHeroes/TourofHeroes/bin/Release/netstandard2.1/wwwroot
        # The name of the remote branch that publishing source for GitHub Pages site
        branch: master
        # The remote repository that publishing source for GitHub Pages site, defaults to current repo and is formatted like 'user/repo-name'
        repo: gopkumr/BlazorHost
        # The personal access token that authorize repo access
        token: d5dbef34df77f3df58ac808583c22c06bfa7e203
