name: .NET Core

on:
  push:
    branches: [ Perf ]
  pull_request:
    branches: [ Perf ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --no-restore "/home/runner/work/BlazorTourOfHeroes/BlazorTourOfHeroes/TourofHeroes/TourofHeroes.csproj"
    - name: GitHub Pages action
      uses: awb-pw/deploy-to-github-pages-action@1.1.1
      with:
        # Author
        AUTHOR: Gopakumar
        # Name of GitHub page repository
        GITHUB_PAGE_NAME: BlazorHost
        # GitHub Personal Access Token
        PA_TOKEN: ebf903936d1b5771b53d05ca0c88f0db88ce7a99
        # Name of build directory
        BUILD_PATH: TourofHeroes/bin/Release/netstandard2.1/wwwroot
        # Who to greet
        USERNAME: gopkumr
        # Who to greet
        EMAIL: gopakumar.r@live.com
        
