name: .NET Core

on:
  push:
    branches: [ Perf ]
  pull_request:
    branches: [ Perf ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --no-restore "/home/runner/work/BlazorTourOfHeroes/BlazorTourOfHeroes/TourofHeroes/TourofHeroes.csproj"
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with: 
        personal_token: 0e6e00a1bba4db20251dbe7c37cc13172d766f83 
        # Set a target branch for deployment.
        publish_branch: master
        # Set an input directory for deployment.
        publish_dir: /TourofHeroes/bin/Release/netstandard2.1/wwwroot
        # Set an external repository (owner/repo).
        external_repository: gopkumr/BlazorHost
        # Set Git user.name
        user_name: gopkumr
        user_email: gopakumar.r@live.com 
        # Set a custom commit message with a triggered commit hash
        commit_message: Auto Deploy
        # Set a custom full commit message without a triggered commit hash
        full_commit_message: This is a deployment from Github Actions
        # An alias for enable_jekyll to disable adding .nojekyll file to master or gh-pages branches
        disable_nojekyll: false
        
