name: .NET Core

on:
  push:
    branches: [ Perf ]
  pull_request:
    branches: [ Perf ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --no-restore "/home/runner/work/BlazorTourOfHeroes/BlazorTourOfHeroes/TourofHeroes/TourofHeroes.csproj"
    - name: GitHub Pages action
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        # GitHub repository where assets will be deployed (default current)
        repo: gopkumr/BlazorHost
        # Git branch where assets will be deployed
        target_branch: master
        # Build directory to deploy
        build_dir: TourofHeroes/bin/Release/netstandard2.1/publish
        # The committer name and email address
        committer: gopkumr <gopakumar.r@live.com>
        # The author name and email address
        author: Gopakumar gopakumar.r@live.com
        # Commit message
        commit_message: deployingpages
      env:
         GH_PAT: gopkumr:ebf903936d1b5771b53d05ca0c88f0db88ce7a99        
